class Page(object):
    # Initalizes the page class
    def __init__(self):
        # These are private variables that can only be modified from outside the class through the use of a setter
        self.__title = "This Shouldent Be Here"
        # Error is a placeholder in this variable, it will be replaced by a function below.
        self.__current_animal = "ERROR"
        # This variable holds the first part of my HTML code.
        self.head = """
<!DOCTYPE HTML>
<html>
    <head>
        <title>{self.title}</title>
        <link href="css/styles.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        """

        # Second part of my HTML code, this holds the Navigation for my page.
        self.__body = """
            <ul>
                <li><a href="?animal=0">Komodo Dragon</a></li>
                <li><a href="?animal=1">Hummingbird</a></li>
                <li><a href="?animal=2">Human Being</a></li>
            </ul>
        """
        # This section of HTML code will hold the info about each camera deal. It will be generated by a setter below.
        self.__display = """
            <h1 class='Home'>Click One of Our Packages to See Our Current Deals</h1><br/>
            """
        # This is the closing section of my HTML, it will not be changed
        self.close = """
    </body>
</html>"""
        # This variable is used to store all of the HTML code. It will be compiled by the update function
        self.whole_page = ""

        # This is used to concatenate all HTML sections that need to be pushed to the page
    def update(self):
        self.whole_page = self.head + self.body + self.display + self.close
        # This checks for and { } references and changes them to the appropriate value from its variable
        self.whole_page = self.whole_page.format(**locals())