class Page(object):
    # Initalizes the page class
    def __init__(self):
        # These are private variables that can only be modified from outside the class through the use of a setter
        self.__title = "This Shouldent Be Here"
        # Error is a placeholder in this variable, it will be replaced by a function below.
        self.__current_animal = "ERROR"
        # This variable holds the first part of my HTML code.
        self.head = """
<!DOCTYPE HTML>
<html>
    <head>
        <title>{self.title}</title>
        <link href="css/styles.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        """

        # Second part of my HTML code, this holds the Navigation for my page.
        self.__body = """
            <ul>
                <li><a href="?animal=0">Komodo Dragon</a></li>
                <li><a href="?animal=1">Hummingbird</a></li>
                <li><a href="?animal=2">Human Being</a></li>
            </ul>
        """
        # This section of HTML code will hold the info about each camera deal. It will be generated by a setter below.
        self.__display = """
            <h1 class='Home'>Click One of Animals to Learn More</h1><br/>
            """
        # This is the closing section of my HTML, it will not be changed
        self.close = """
    </body>
</html>"""
        # This variable is used to store all of the HTML code. It will be compiled by the update function
        self.whole_page = ""
        self.__section = ""

        if self.__current_animal != "ERROR":
            self.__section = """
            <img src="{self.current_animal.url}" alt="Image of {self.current_animal.name}" />
            <p>{self.current_animal.name}</p>
            <p>{self.current_animal.phylum}</p>
            <p>{self.current_animal.klass}</p>
            <p>{self.current_animal.family}</p>
            <p>{self.current_animal.genus}</p>
            <p>{self.current_animal.lifespan}</p>
            <p>{self.current_animal.habitat}</p>
            <p>{self.current_animal.geolocation}</p>
            """


        # This is used to concatenate all HTML sections that need to be pushed to the page
    def update(self):
        self.whole_page = self.head + self.__body + self.__section + self.close
        # This checks for and { } references and changes them to the appropriate value from its variable
        self.whole_page = self.whole_page.format(**locals())

    @property
    def title(self):
        return self.__title

    @title.setter
    def title(self, new_title):
        self.__title = new_title
        return self.__title

    @property
    def current_animal(self):
        return self.__current_animal

    @current_animal.setter
    def current_animal(self, new_animal):
        self.__current_animal = new_animal
        self.update()

    @property
    def section(self):
        return self.__section

    @section.setter
    def section(self, new_section):
        self.__section = new_section
        self.update()


